### ISSUE TITLE
What computer does if it's RAM is FULL

### ISSUE THREAD

**Issue by raiftekin** [AnastasiaRomanenko/MyWeeklyReports#1]
According to your notes, we definitely need CPU and RAM computer to work. Suppose that os is working and because of one application, it's ram started to be filled. How would the computer react?  Does it have precautions to avoid system breaks?

**Comment by AnastasiaRomanenko** [comment]
Here's how a computer might react if RAM is full:

- The operating system goes to the hard disk to overlay the old data in RAM with new data. This allows the system to free up RAM for more immediate tasks. But this process slows the computer's operation. 

- Some modern operating systems, like macOS and Windows 10/11, use memory compression techniques to reduce the size of data in RAM.

- The operating system's OOM (Out of Memory) manager identifies and terminates processes that are using a lot of memory but are of lower priority.

- Before reaching a critical point, the operating system may alert users that memory is running low, allowing them to close some applications or take other actions to free up memory.

- If an application requests more memory than what is available, the application may crash or be terminated by the operating system, often with an error message. This prevents the entire system from crashing.

- Operating systems typically allocate memory based on process priority. High-priority system services will receive memory allocation before lower-priority user applications. This helps ensure that critical system processes continue to run smoothly even in low-memory conditions.

- In systems with managed runtimes (like Java), garbage collection can help free up memory by automatically reclaiming memory that is no longer in use by the application.
